name: CI - Test and Coverage

on:
  pull_request:
    branches: [dev]

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests with coverage
        run: npx vitest run --coverage --silent

      - name: Enforce minimum coverage (>= 70%)
        run: |
          TOTAL=$(node -pe "require('./coverage/coverage-summary.json').total.statements.pct")
          echo "Total statement coverage: $TOTAL%"
          if [ "$TOTAL" -lt 70 ]; then
            echo "Coverage is below 70%"
            exit 1
          else
            echo "Coverage is acceptable (>= 70%)"
          fi

      - name: Post-job success
        if: success()
        run: echo "🎉 Pipeline finalizado correctamente. ¡Todo en orden!"

      - name: Post-job failure
        if: failure()
        run: echo "🚨 El pipeline falló. Revisa los errores y el nivel de cobertura."
